import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AdminWrapper from "./components/layout/AdminWrapper";
import LenisProvider from "./components/layout/LenisProvider";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const anekLatin = localFont({
  variable: "--font-anek",
  src: [
    {
      // AnekLatin-Thin.ttf
      path: "../public/font/AnekLatin-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/font/AnekLatin-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/font/AnekLatin-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/font/AnekLatin-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/AnekLatin-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/font/AnekLatin-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/font/AnekLatin-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/font/AnekLatin-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        anekLatin.variable,
        "font-sans",
        geist.variable
      )}
    >
      <body className="min-h-full flex flex-col">
        <LenisProvider>
          <AdminWrapper>{children}</AdminWrapper>

          {/* WhatsApp Floating Icon */}
          <a
            href="https://wa.me/+971507569611"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Chat on WhatsApp"
            className="fixed right-11 bottom-9 z-[9999] flex h-14 w-14 items-center justify-center rounded-full bg-[#25D366] shadow-lg transition hover:scale-110"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 32 32"
              className="h-8 w-8 fill-white"
            >
              <path d="M16.01 3.2c-7.06 0-12.8 5.74-12.8 12.8 0 2.26.59 4.47 1.72 6.42L3.1 29.2l6.94-1.82a12.72 12.72 0 0 0 5.97 1.52c7.06 0 12.8-5.74 12.8-12.8s-5.74-12.9-12.8-12.9Zm0 23.47c-1.9 0-3.76-.51-5.39-1.48l-.39-.23-4.12 1.08 1.1-4.02-.26-.41a10.52 10.52 0 0 1-1.61-5.61c0-5.84 4.75-10.59 10.59-10.59S26.52 10.16 26.52 16s-4.67 10.67-10.51 10.67Zm5.81-7.93c-.32-.16-1.89-.93-2.18-1.04-.29-.11-.5-.16-.71.16-.21.32-.82 1.04-1.01 1.25-.18.21-.37.24-.69.08-.32-.16-1.35-.5-2.57-1.59-.95-.85-1.59-1.9-1.78-2.22-.18-.32-.02-.49.14-.65.14-.14.32-.37.48-.56.16-.18.21-.32.32-.53.11-.21.05-.4-.03-.56-.08-.16-.71-1.7-.97-2.33-.26-.61-.52-.53-.71-.54h-.61c-.21 0-.56.08-.85.4-.29.32-1.12 1.09-1.12 2.66s1.15 3.09 1.31 3.3c.16.21 2.26 3.45 5.47 4.84.76.33 1.36.53 1.83.68.77.24 1.47.21 2.02.13.62-.09 1.89-.77 2.16-1.52.27-.75.27-1.39.19-1.52-.08-.13-.29-.21-.61-.37Z" />
            </svg>
          </a>
        </LenisProvider>
      </body>
    </html>
  );
}