/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, MeshTransmissionMaterial } from "@react-three/drei";

export function Model({
  rotationY   = 0,
  rotationX   = 0,
  rotationZ   = 0,
  glassFactor = 0,   // 0 = steel, 1 = glass (Hero2 only) — static fallback
  glassFactorRef,    // preferred: read fresh every frame, bypasses React re-renders
  ...props
}) {
  const { nodes, materials } = useGLTF("/iTOIlw.glb");
  const orig = materials.Material; // original GLTF material — never mutated

  const steelRef = useRef();
  const glassRef = useRef();

  useFrame(() => {
    if (!steelRef.current || !glassRef.current) return;
    const gf = glassFactorRef ? glassFactorRef.current : glassFactor;
    // Simple threshold swap — glass visible only in Hero2 (glassFactor ≥ 0.5)
    steelRef.current.visible = gf < 0.5;
    glassRef.current.visible = gf >= 0.5;
  });

  const sharedProps = {
    castShadow:    true,
    receiveShadow: true,
    geometry:      nodes.Curve001.geometry,
    position:      [0, 0.63, 0],
    rotation:      [Math.PI / 2, 0, -1.178],
    scale:         74.687,
  };

  return (
    <group
      scale={[3, 3, 3]}
      rotation-x={rotationX}
      rotation-y={rotationY}
      rotation-z={rotationZ}
      {...props}
      dispose={null}
    >
      {/* Steel — original GLTF material, looks exactly like before */}
      <mesh ref={steelRef} {...sharedProps} material={orig} />

      {/* Glass — MeshTransmissionMaterial for proper refraction + chromatic aberration */}
      <mesh ref={glassRef} {...sharedProps} visible={false}>
        <MeshTransmissionMaterial
          samples={8}
          transmission={0.65}
          thickness={0.08}
          roughness={0.05}
          ior={1.25}
          chromaticAberration={0.008}
          backside={false}
          color="#ddeeff"
          envMapIntensity={1.8}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/iTOIlw.glb");
