/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useMemo, useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, MeshTransmissionMaterial } from "@react-three/drei";

export function Model({
  rotationY   = 0,
  rotationX   = 0,
  rotationZ   = 0,
  glassFactor = 0,   // 0 = steel, 1 = glass (Hero2 only) — static fallback
  glassFactorRef,    // preferred: read fresh every frame, bypasses React re-renders
  ...props
}) {
  const { nodes, materials } = useGLTF("/iTOIlw.glb");
  const orig = materials.Material; // original GLTF material — never mutated

  // The monochrome studio HDRI is a bright, mostly-white cyclorama — nearly
  // every direction the metal can reflect is bright, so raising roughness
  // made it worse (it averages in MORE of that uniform brightness instead
  // of a small mirror hotspot with darker reflections elsewhere). The actual
  // fix is cutting envMapIntensity hard and darkening the base color so even
  // a full-strength reflection doesn't clip to pure white.
  const steelMat = useMemo(() => {
    const mat = orig.clone();
    mat.color.set("#8a8f96");
    mat.envMapIntensity = 0.22;
    return mat;
  }, [orig]);

  const steelRef = useRef();
  const glassRef = useRef();

  useFrame(() => {
    if (!steelRef.current || !glassRef.current) return;
    const gf = glassFactorRef ? glassFactorRef.current : glassFactor;
    // Simple threshold swap — glass visible only in Hero2 (glassFactor ≥ 0.5)
    steelRef.current.visible = gf < 0.5;
    glassRef.current.visible = gf >= 0.5;
  });

  const sharedProps = {
    castShadow:    true,
    receiveShadow: true,
    geometry:      nodes.Curve001.geometry,
    position:      [0, 0.63, 0],
    rotation:      [Math.PI / 2, 0, -1.178],
    scale:         74.687,
  };

  return (
    <group
      scale={[3, 3, 3]}
      rotation-x={rotationX}
      rotation-y={rotationY}
      rotation-z={rotationZ}
      {...props}
      dispose={null}
    >
      {/* Steel — cloned material, envMapIntensity dialed down to reduce blowout */}
      <mesh ref={steelRef} {...sharedProps} material={steelMat} />

      {/* Glass — MeshTransmissionMaterial for proper refraction + chromatic aberration */}
      <mesh ref={glassRef} {...sharedProps} visible={false}>
        <MeshTransmissionMaterial
          samples={8}
          transmission={0.65}
          thickness={0.08}
          roughness={0.05}
          ior={1.25}
          chromaticAberration={0.008}
          backside={false}
          color="#ddeeff"
          envMapIntensity={0.6}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/iTOIlw.glb");
