/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model({
  rotationY = 0,
  rotationX = 0,
  rotationZ = 0,
  ...props
}) {
  const { nodes, materials } = useGLTF("/iTOIlw.glb");
  return (
    <group scale={[3, 3, 3]} rotation-x={rotationX} rotation-y={rotationY} rotation-z={rotationZ} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve001.geometry}
        material={materials.Material}
        position={[-0.2, 0.63, 0.227]}
        rotation={[Math.PI / 2, 0, -1.178]}
        scale={74.687}
      />
    </group>
  );
}

useGLTF.preload("/iTOIlw.glb");
